<!-- ======= Header/Navbar ======= -->
  <nav class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top">
    <div class="container">
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDefault" aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <a class="navbar-brand text-brand" href="index.php">Estate<span class="color-b">Agency</span></a>

      <div class="navbar-collapse collapse justify-content-center" id="navbarDefault">
        <ul class="navbar-nav">

          <li class="nav-item">
            <a class="nav-link " href="index.php">Home</a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="property-grid.php">Property</a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="stats.php">Statistics</a>
          </li>

          
          <li class="nav-item">
            <a class="nav-link " href="contact.php">Contact</a>
          </li>
          
        </ul>
      </div>


    </div>
  </nav><!-- End Header/Navbar -->